DirtyStreetNames <- c(" LAKESIDE DRIVE", " ORANGE GROVE ROAD", " TOMLINSON  ROAD ", 
                      " MEYAPPA   CHETTIAR   ROAD", "  ANDERSON     ROAD", "WILKIE     TERRACE  ", 
                      " HILLSIDE  DRIVE", "  SUNBIRD     ROAD ", " HILLVIEW     AVENUE ", 
                      "  KALIDASA  AVENUE  ", "WATTEN VIEW", " HOOT  KIAM  ROAD ", 
                      " MOUNT  VERNON  ROAD ", "KIM   SENG   WALK  ", " LUCKY    HEIGHTS ", 
                      "DERBYSHIRE ROAD  ", "  BROOKVALE WALK ", "  OXFORD ROAD  ", 
                      "SOUTH     BUONA     VISTA     ROAD", "STILL    ROAD", "HAIG     ROAD", 
                      "CRAIG  ROAD", "MARINE     PARADE", " ELLIOT    ROAD  ", " STEVENS CLOSE ", 
                      " DRAYCOTT     DRIVE", "  TAN QUEE LAN STREET ", "  SPOTTISWOODE    PARK    ROAD ", 
                      " PEARL   BANK ", "KHEAM    HOCK    ROAD  ", "KIM    SENG    ROAD", 
                      " WOODGROVE  DRIVE ", "  SIMS     AVENUE  ", " JALAN   MASJID", 
                      "LINCOLN     ROAD  ", "  MARNE  ROAD  ", "  LEWIS  ROAD", "  ORCHARD    ROAD ", 
                      " NAPIER    ROAD ", "  EVERITT    ROAD  ")
