DirtyStreetNames <- c("ONTARIO   AVENUE", " THOMSON HILLS DRIVE", " LAKESIDE DRIVE", 
                      " ORANGE GROVE ROAD", " TOMLINSON  ROAD ", " MEYAPPA   CHETTIAR   ROAD", 
                      "  ANDERSON     ROAD", "WILKIE     TERRACE  ", "  HULLET   ROAD ", 
                      "MISTRI    ROAD  ", "JALAN  SERENE ", "LORONG    H    TELOK    KURAU ", 
                      "  HAZEL   PARK   TERRACE  ", " HILLSIDE  DRIVE", "JALAN    SELANTING  ", 
                      "  SUNBIRD     ROAD ", "LEONIE   HILL   ROAD ", " HILLVIEW     AVENUE ", 
                      "  KALIDASA  AVENUE  ", "WATTEN VIEW", " HOOT  KIAM  ROAD ", 
                      " MOUNT  VERNON  ROAD ", "KIM   SENG   WALK  ", "  BUKIT     DRIVE", 
                      "SANDILANDS  ROAD", " LUCKY    HEIGHTS ", "DERBYSHIRE ROAD  ", 
                      "  BROOKVALE WALK ", "  OXFORD ROAD  ", "HOW     SUN     DRIVE  ", 
                      "SOUTH     BUONA     VISTA     ROAD", "STILL    ROAD", "HAIG     ROAD", 
                      "CRAIG  ROAD", "MARINE     PARADE", " ELLIOT    ROAD  ", "JALAN     NAUNG", 
                      " STEVENS CLOSE ", "  LORONG 1 REALTY PARK", " DRAYCOTT     DRIVE", 
                      "  TAN QUEE LAN STREET ", " JALAN   SAUDARA   KU  ", " THOMSON   LANE", 
                      "  SPOTTISWOODE    PARK    ROAD ", "CORONATION     ROAD", " PEARL   BANK ", 
                      "KHEAM    HOCK    ROAD  ", "KIM    SENG    ROAD", " WOODGROVE  DRIVE ", 
                      "  SIMS     AVENUE  ", " JALAN   MASJID", "LINCOLN     ROAD  ", 
                      "  MARNE  ROAD  ", "  LEWIS  ROAD", "EVERITT   ROAD   NORTH ", 
                      "PULASAN ROAD  ", "  ORCHARD    ROAD ", "BUKIT  BATOK  CENTRAL  LINK ", 
                      " NAPIER    ROAD ", "  EVERITT    ROAD  ", "MINBU    ROAD", "  TANAH MERAH KECHIL AVENUE  ", 
                      "BISHOPSGATE  ", "  UPPER CHANGI ROAD EAST  ", " ZEHNDER   ROAD", 
                      " CAIRNHILL   CIRCLE ", " FARRER   ROAD", "  CORONATION  ROAD  WEST  ", 
                      "  UPPER    SERANGOON    VIEW  ", "  DELTA   ROAD  ", "DEPOT   ROAD", 
                      "  ANG   MO   KIO   AVENUE   1 ", "MANGIS   ROAD", "  RIVERVALE    LINK  ", 
                      "  EVERTON  ROAD ", "IRRAWADDY    ROAD", "  LORONG  108  CHANGI", 
                      "  FABER DRIVE  ", " BIDEFORD    ROAD", " FERNWOOD  TERRACE  ", 
                      "LORONG AMPAS ", " ALEXANDRA     VIEW ", " CHIN   SWEE   ROAD", 
                      " TOH  TUCK  ROAD  ", "JALAN     PASIR     RIA  ", "  LEITH PARK ", 
                      "  HOUGANG     STREET     32", "  FIGARO  STREET  ", " JALAN KEMBANGAN ", 
                      "PUNGGOL  WALK  ", "ANTHONY     ROAD", "  DUCHESS ROAD ", "MOUNT     SINAI     RISE", 
                      " JALAN     RAJAWALI  ", "HUME    AVENUE  ", "LORONG    4    GEYLANG ", 
                      "YONG SIAK STREET  ", " HOLT   ROAD", "  TEOW   HOCK   AVENUE  ", 
                      " DAISY   ROAD  ")